In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
x = np.array([5,15,25,35,45,55]).reshape(-1,1)
y = np.array([5,20,14,32,22,38])
print(x)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]


In [3]:
model = LinearRegression()
model.fit(x,y)


LinearRegression()

In [4]:
model = LinearRegression().fit(x,y)

In [5]:
r_sq = model.score(x,y)

In [6]:
print('coefficient of determination:',r_sq)

coefficient of determination: 0.715875613747954


In [7]:
print('intercept:', model.intercept_)
print('slope:',model.coef_)

intercept: 5.633333333333329
slope: [0.54]


In [8]:
y_pred = model.predict(x)
print('predict response:',y_pred,sep="\n")

predict response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [9]:
y_pred = model.intercept_+model.coef_*x
print('predicted response:',y_pred,sep="\n")

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]
